### PR TITLE
Enhance Lawn Mower Activity State Handling and Update Compatibility

### PR DESCRIPTION
**Pull request by Whytey**
### **User description**
As described in https://developers.home-assistant.io/blog/2024/08/23/lawn-mower-activity-returning/

___

### **Description**
- Enhanced the lawn mower activity state handling by adding support for the `LawnMowerActivity.RETURNING` state.
- Updated the Home Assistant compatibility version to `2024.9.0`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>lawn_mower.py</strong><dd><code>Enhance Lawn Mower Activity State Handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

custom_components/mammotion/lawn_mower.py
<li>Added handling for the <code>LawnMowerActivity.RETURNING</code> state.<br> <li> Updated logic to return <code>LawnMowerActivity.RETURNING</code> when in <br><code>WorkMode.MODE_RETURNING</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/mikey0000/Mammotion-HA/pull/112/files#diff-3af9b47c563d00133985b13d37c0fb657cc947de1f4c7feae8bdeb8d849de9d7">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
</table></td></tr><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>hacs.json</strong><dd><code>Update Home Assistant Compatibility Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

hacs.json
- Updated Home Assistant version from `2024.5.0` to `2024.9.0`.

</details>

  </td>
  <td><a href="https://github.com/mikey0000/Mammotion-HA/pull/112/files#diff-2004f3033aaa650b74a155b56a1e6110e85583824c83f3cb5a0c2856bd00483f">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
</table></td></tr></tr></tbody></table>

### CODE REVIEW

**Comment by mikey0000** [comment]
That was fast, I'm not going to merge this till probably oct/Nov to give people time to update.

**Comment by Whytey** [comment]
> You'd possibly be aware I'm the one who added the returning type?

I did not, no.  Nicely done!

Understand waiting for others to update their instances.  An alternative would be to put some conditions in there if you wish - depends how complicated you want your integration to be.

**Comment by mikey0000** [comment]
I'd accept conditionals

**Comment by mikey0000** [comment]
I should add I'm only waiting till nov/dec

**Pull request merged**
